export const COLORS_ACTIONS = {
  INCREAMENTS: {
    RED: "INCREAMENT_RED",
    GREEN: "INCREAMENT_GREEN",
    BLUE: "INCREAMENT_BLUE",
  },
  DECREAMENTS: {
    RED: "DECREAMENT_RED",
    GREEN: "DECREAMENT_GREEN",
    BLUE: "DECREAMENT_BLUE",
  },
  RESET: "RESET",
};
